### ISSUE TITLE
"File is not in the repository's workdir" Error on Windows

### ISSUE THREAD

**Issue by PigeonF** [gitext-rs/git-dive#68]
I wanted to test the project on Windows, but when running `git dive` I get an error about the file not being part of the repository's workdir.

```console
$ git-dive --version
git-dive 0.1.3
$ git clone https://github.com/gitext-rs/git-dive/
$ cd git-dive
$ git dive Cargo.toml
File \\?\C:\Users\pigeon\git\github.com\gitext-rs\git-dive\Cargo.toml is not in the repository's workdir C:/Users/pigeon/git/github.com/gitext-rs/git-dive/
```

Presumably this is a false positive related to windows extended length path shenanigans?

If you need more detailed logs please let me know.

**Comment by epage** [comment]
Thanks for reporting this!

**Comment by PigeonF** [comment]
Can confirm that the latest release fixed the issue! Thanks!
